js/content.js, js/popup.js, popup.html
#1
- Add checkbox setting to the bottom of popup panel
=> Can hide original role history

README.md, js/content.js
=> Support multi base accounts

js/content.js, manifest.json
=> Fix to get account id that is alias

README.md, manifest.json
=> Apply to Personal Health Dashboard

popup.html, src/popup.js
Hello !
I've noticed the word "configuration" contained a typo, so i fixed it.
I don't know if i have to increase the version number in this PR, so let me know :)
Thanks!
=> fix english wording of "configuration"

popup.html, src/content.js, src/popup.js
=> Add `hide acccount id` check box

manifest.json, package.json, popup.html
- wide textarea and set its spellcheck off
- modify color input
=> Update popup style

manifest.json, manifest_firefox.json, popup.html, src/content.js
=> Keep contrast of profile label

manifest.json, manifest_firefox.json, package.json, src/sanitizer.js
=> Fix to load Sanitizer on CFn page

manifest_firefox.json
=> Remove max version limitation

.travis.yml, karma.conf.js, package.json
https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai
=> Use headless Chrome instead of PhantomJS

README.md, src/lib/content.js, test/content_redirect_uri.test.js, test/content_reset_region.test.js, test/fixtures/data.json
=> Support region to change on switching

bin/build.sh, options.html, src/content.js, src/lib/auto_assume_last_role.js, src/lib/common.js, src/lib/content.js, src/lib/profile.js, src/options.js, test/content_auto_assume_last_role.test.js, test/helper.test.js
=> Add auto-switch to last role

manifest.json, manifest_firefox.json, package.json, src/lib/content.js
Filtering role list by profile name and _Enter_ to switch first matched role
related #52 #61 for v0.10.0
=> Implement role filter

README.md, donation.html
=> Add bitcoin address to Donation

src/lib/data_profiles_splitter.js, test/lib/data_profiles_splitter.test.js
=> Clear splited profile entries remaining

options.html
=> Copy image option explanation to options page

manifest_firefox.json, package.json, src/lib/content.js
=> Fix insert html and version

manifest.json, src/lib/content.js
=> Support AWS Gov region

src/lib/auto_assume_last_role.js
Emulate menu click to set redirect_uri
=> Fix auto switch

src/lib/content.js
=> Enlarge profile image

src/options.js
=> Fix loading raw-text from storage to textarea

src/lib/content.js, src/lib/profile.js, test/content.test.js, test/content_scripts.test.js, test/fixtures/awsmc-exclude-unrelated-profile-from-history.html
Fix to judge input.value without aws_account_id comparing excluded names
=> Fix excluding unrelated profile from history

README.md, options.html
and mark up parameter names as code
=> Refactor the explanations of optional parameters and settings

README.md, options.html, src/lib/profile_set.js, test/content.test.js
=> Implement target_role_name for base account

manifest.json, manifest_firefox.json, package.json, src/lib/profile_set.js
=> Fix switch role definition in the same AWS Account causes empty list

CHANGELOG.md, bin/build.sh, manifest.json, manifest_chrome.json, manifest_firefox.json, package.json, popup.html, src/popup.js, updated.html
- Chrome extesion released
- Firefox add-on released
Fixes #108
=> Release 0.15.0

package.json, yarn.lock
=> Upgrade npm libraries

README.md, options.html
Fix the omission of target_region explanation
=> Explain target_region field in configuration

src/background.js, src/lib/storage_repository.js, src/options.js, src/popup.js, src/supporters.js
introduce Repository pattern classes to be able to select either sync or local of storage area
=> Storage repository

README.md, options.html, src/background.js, src/options.js, src/popup.js
=> Configuration storage setting

package.json, src/lib/load_aws_config.js, src/options.js, test/lib/load_aws_config.test.js
=> Refactor parsing INI format and aws config definitions

src/content.js, src/popup.js
=> Fix switching region

README.md, options.html, src/lib/profile_set.js, test/lib/profile_set.test.js
Fixes #213
rel #212
- fix the explanation configuration
=> role_name is treated as permission set if AWS SSO

CHANGELOG.md, manifest.json, manifest_chrome.json, manifest_firefox.json, package.json, updated.html
- add the explanation for 2.2.0
- merge manifest version
=> Release 2.2.0

CHANGELOG.md, manifest.json, package.json, src/content.js, updated.html
=> Fix to get AWS signin endpoint host

src/attach_target.js, src/popup.js
=> Remove isGlobal no longer used

package-lock.json, package.json, src/lib/create_role_list_item.js, src/popup.js, test/lib/create_role_list_item.test.js
- refactor into renderRoleList and setupRoleFilter
- define createRoleListItem function and add its test
=> Refactor popup.js

src/lib/create_role_list_item.js, src/popup.js, test/lib/create_role_list_item.test.js
=> Refactor popup.js around creating redirect URI

options.html, src/content.js, src/options.js, src/popup.js
=> Sign-in endpoint in current region

src/content.js
=> Skip receiving message in iframes

src/lib/create_role_list_item.js, test/lib/create_role_list_item.test.js
#238 
- set color if an item has only color not image
- set image if an item has only image not color
- set color and image if an item has both color and image
- set gray color if an item have neither color nor image
=> Fix list head style

src/content.js
- functionize loadInfo
- fix to remove script element no longer needed
=> Refactor content script

src/popup.js
isLocal means that current service region equals to current sub domain.
=> Fix to judge isLocal (instead of isGlobal)

test/lib/load_aws_config.test.js
=> Fix error message

options.html, popup.html, src/options.js, src/popup.js
options.html / popup.html 
- inline css updated to contain .dark-mode classes
- added darkModeCheckBox to options.html
options.js
- added check in options.js if dark-mode enabled, then add dark-mode class. 
- added darkMode to booleanSettings const
popup.js 
- added check in options.js if dark-mode enabled, then add dark-mode class.
Resolves: #210
=> feat: add darkmode 

options.html, popup.html, src/options.js, src/popup.js
#289 conitnued
You can select browser default, light or dark.
=> Visual mode

manifest.json
=> Modify the AWS matching host

.github/workflows/test.yml, playwright.config.ts, test/emulator/fixtures.js
- Update actions/checkout@v3, actions/setup-node@v3
- Add Playwright config
=> Fix GitHub Actions workflow

src/js/handlers/update_profiles.js, src/js/lib/compressed_text_splitter.js, src/js/lib/compressed_text_splitter.test.js, src/js/options.js, src/test/update_profiles.test.js
=> Fix managing configuration

CHANGELOG.md, bin/archive.sh, manifest.json, src/updated.html
=> Release v4.0.0

test/extension/background.js
Change from a JSONized string comparison method to a recursive field comparison of objects.
=> Update assert function

manifest.json, src/js/content.js
=> Change run_at document_end

package-lock.json, package.json
=> Upgrade aesr-config to v0.4.1

src/js/lib/target_profiles.js
=> Fallback to retrieve profiles during Firefox private browsing

CHANGELOG.md, manifest.json, package.json, src/js/lib/target_profiles.js, src/updated.html
* Fix to call retrieveTargetProfilesFromLztext
=> Release 4.0.3

.github/workflows/test.yml
Fix using deprecated actions packages
=> Update checkout and setup-node for GH Actions

src/js/lib/target_profiles.js
refactoring function name and processing
=> Modify role filtering to match only the leaf

package-lock.json, package.json
* upgrade dev libs
* fix audit
=> Upgrade devDependencies libraries

bin/setup_manifest.mjs
=> Fix calling hasOwn in setup_manifest.mjs
